# TreeSAPP reference packages

<!-- Current list of TreeSAPP reference packages, get newest version from https://github.com/hallamlab/RefPkgs/wiki/refpkgs -->

+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| Name                                                                                                                            | Description                                                                              | Leaf nodes | Pathway                                       | Cycle |
+:================================================================================================================================+:=========================================================================================+:===========+:==============================================+:======+
| [AA10](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/AA10/seed_refpkg/final_outputs)                                 | Auxiliary Activity family 10                                                             | 699        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [GH101](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/GH101/seed_refpkg/final_outputs)                               | Glycoside hydrolase family 101                                                           | 113        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [GH102](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/GH102/seed_refpkg/final_outputs)                               | Glycoside hydrolase family 102                                                           | 727        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [GH103](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/GH103/seed_refpkg/final_outputs)                               | Glycoside hydrolase family 103                                                           | 1145       | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [GH109](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/GH109/seed_refpkg/final_outputs)                               | Glycoside hydrolase family 109                                                           | 376        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [GH115](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/GH115/seed_refpkg/final_outputs)                               | Glycoside hydrolase family 115                                                           | 267        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [GH126](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/GH126/seed_refpkg/final_outputs)                               | Glycoside hydrolase family 126                                                           | 112        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [GH163](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/GH163/seed_refpkg/final_outputs)                               | Glycoside hydrolase family 163                                                           | 102        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [GH67](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/GH67/seed_refpkg/final_outputs)                                 | Glycoside hydrolase family 67                                                            | 372        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [GH94](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/GH94/seed_refpkg/final_outputs)                                 | Glycoside hydrolase family 94                                                            | 695        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [McrA](https://github.com/hallamlab/RefPkgs/blob/master/Methanogenesis/McrA/MAG_update_RaxML-NG/final_outputs)                  | Methyl coenzyme M reductase alpha subunit                                                | 424        | Methanogenesis                                | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [McrA](https://github.com/hallamlab/RefPkgs/blob/master/Methanogenesis/McrA/seed_refpkg/final_outputs)                          | Methyl coenzyme M reductase alpha subunit                                                | 249        | Methanogenesis                                | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [McrB](https://github.com/hallamlab/RefPkgs/blob/master/Methanogenesis/McrB/seed_refpkg/final_outputs)                          | Methyl coenzyme M reductase beta subunit                                                 | 110        | Methanogenesis                                | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [McrG](https://github.com/hallamlab/RefPkgs/blob/master/Methanogenesis/McrG/seed_refpkg/final_outputs)                          | Methyl coenzyme M reductase gamma subunit                                                | 123        | Methanogenesis                                | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PHAdeg](https://github.com/hallamlab/RefPkgs/blob/master/Hydrocarbons/PHA_degradation/PHA_depolymerases/final_outputs)         | Poly(hydroxyalkanoate) degradation enzymes                                               | 10         | Plastics degradation                          | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PL11](https://github.com/hallamlab/RefPkgs/blob/master/CAZymes/PL11/seed_refpkg/final_outputs)                                 | Polysaccharide lyase family 11                                                           | 320        | Carbohydrate metabolism                       | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PuhA](https://github.com/hallamlab/RefPkgs/blob/master/Photosynthesis/PuhA/seed_refpkg/final_outputs)                          | photosynthetic reaction center H subunit                                                 | 47         | Photosynthesis                                | C     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PilA](https://github.com/hallamlab/RefPkgs/blob/master/Direct_Interspecies_Electron_Transfer/pillin/seed_refpkg/final_outputs) | Type IV pilin N-terminus, including PilA                                                 | 70         | Direct interspecies electron transfer         | E     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [HydA](https://github.com/hallamlab/RefPkgs/blob/master/Hydrogen/HydA/seed_refpkg/final_outputs)                                | [FeFe] hydrogenase, group A, B1, B3                                                      | 93         | Hydrogenase                                   | H     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [HgcA](https://github.com/hallamlab/RefPkgs/blob/master/Mercury/HgcA/seed_refpkg/final_outputs)                                 | Methylmercury active enzyme, subunit A                                                   | 108        | NA                                            | Hg    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [HgcB](https://github.com/hallamlab/RefPkgs/blob/master/Mercury/HgcB/seed_refpkg/final_outputs)                                 | Methylmercury active enzyme, subunit B                                                   | 122        | NA                                            | Hg    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NapA](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Denitrification/NapA/seed_refpkg/final_outputs)     | Periplasmic nitrate reductase, large subunit                                             | 765        | Denitrification                               | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NifD](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Fixation/NifD/seed_refpkg/final_outputs)            | nitrogenase molybdenum-iron protein alpha chain                                          | 926        | Nitrogen fixation                             | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NifH](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Fixation/NifH/seed_refpkg/final_outputs)            | Nitrogenase iron protein [TIGR01287,EC:1.18.6.1]                                         | 660        | Nitrogen fixation                             | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NirK](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Denitrification/NirK/seed_refpkg/final_outputs)     | nitrite reductase (NO-forming)                                                           | 325        | Denitrification,Annamox                       | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NirS](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Denitrification/NirS/seed_refpkg/final_outputs)     | nitrite reductase (NO-forming) / hydroxylamine reductase                                 | 511        | Denitrification,Annamox                       | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NorB](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Denitrification/NorB/seed_refpkg/final_outputs)     | nitric oxide reductase subunit B                                                         | 460        | Denitrification                               | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NorC](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Denitrification/NorC/seed_refpkg/final_outputs)     | nitric oxide reductase subunit C                                                         | 173        | Denitrification                               | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NosZ](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Denitrification/NosZ/seed_refpkg/final_outputs)     | Nitrous-oxide reductase (TAT-dependent\|Sec-dependent)                                   | 26         | Denitrification                               | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NxrA](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Denitrification/NxrA/seed_refpkg/final_outputs)     | nitrate reductase / nitrite oxidoreductase, alpha subunit                                | 658        | Nitrification                                 | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [NxrB](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Nitrification/NxrB/seed_refpkg/final_outputs)       | nitrate reductase / nitrite oxidoreductase, beta subunit                                 | 648        | Nitrification                                 | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [XmoA](https://github.com/hallamlab/RefPkgs/blob/master/Nitrogen_metabolism/Nitrification/XmoA/XmoA_seed/final_outputs)         | Alpha subunits of copper membrane monooxygenase enzymes                                  | 37         | Nitrification                                 | N     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF00380a](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF00380/seed_refpkg_arc/final_outputs)                  | Ribosomal protein S9/S16                                                                 | 82         | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF00380b](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF00380/seed_refpkg_bac/final_outputs)                  | Ribosomal protein S9/S16                                                                 | 1065       | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF00410a](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF00410/seed_refpkg_arc/final_outputs)                  | Ribosomal protein S8                                                                     | 155        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF00410b](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF00410/seed_refpkg_bac/final_outputs)                  | Ribosomal protein S8                                                                     | 1216       | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF00687a](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF00687/seed_refpkg_arc/final_outputs)                  | Ribosomal protein L1p/L10e family                                                        | 192        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF00687b](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF00687/seed_refpkg_bac/final_outputs)                  | Ribosomal protein L1p/L10e family                                                        | 864        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF00750a](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF00750/seed_refpkg_arc/final_outputs)                  | tRNA synthetases class I (R)                                                             | 193        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF00750b](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF00750/seed_refpkg_bac/final_outputs)                  | tRNA synthetases class I (R)                                                             | 1317       | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF00900](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF00900/seed_refpkg/final_outputs)                       | Ribosomal family S4e                                                                     | 328        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF01015](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF01015/seed_refpkg/final_outputs)                       | Ribosomal S3Ae family                                                                    | 101        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF01092](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF01092/seed_refpkg/final_outputs)                       | Ribosomal protein S6e                                                                    | 169        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF01157](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF01157/seed_refpkg/final_outputs)                       | Ribosomal protein L21e                                                                   | 74         | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF01200](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF01200/seed_refpkg/final_outputs)                       | Ribosomal protein S28e                                                                   | 129        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF01280](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF01280/seed_refpkg/final_outputs)                       | Ribosomal protein L19e                                                                   | 281        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF01409a](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF01409/seed_refpkg_arc/final_outputs)                  | tRNA synthetases class II core domain (F)                                                | 243        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF01409b](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF01409/seed_refpkg_bac/final_outputs)                  | tRNA synthetases class II core domain (F)                                                | 891        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF01655](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF01655/seed_refpkg/final_outputs)                       | Ribosomal protein L32                                                                    | 220        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [PF01866](https://github.com/hallamlab/RefPkgs/blob/master/Translation/PF01866/seed_refpkg/final_outputs)                       | Putative diphthamide synthesis protein                                                   | 229        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [RpoB](https://github.com/hallamlab/RefPkgs/blob/master/Translation/RpoB/seed_refpkg/final_outputs)                             | RNA polymerase beta subunit                                                              | 697        | Translation                                   | NA    |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [CysD](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/CysD/seed_refpkg/final_outputs)                       | sulfate adenylyltransferase (SAT), small subunit                                         | 93         | Assimilatory sulfate reduction                | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [CysH](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/CysH/seed_refpkg/final_outputs)                       | phosophoadenylyl-sulfate reductase [PF01507, EC:1.8.4.8\|1.8.4.10]                       | 710        | Assimilatory sulfate reduction                | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [CysI_Sir](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/CysI_Sir/seed_refpkg/final_outputs)               | (assimilatory) sulfite reductase (NADPH) hemoprotein, beta subunit\|ferredoxin dependent | 1055       | Assimilatory sulfate reduction                | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [CysJ](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/CysJ/seed_refpkg/final_outputs)                       | sulfite reductase [NADPH] flavoprotein, alpha-component [COG0369, EC:1.8.1.2]            | 474        | Assimilatory sulfate reduction                | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [CysN](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/CysN/seed_refpkg/final_outputs)                       | Sulfate adenylyltransferase (SAT), large subunit                                         | 1221       | Assimilatory sulfate reduction                | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [DsrAB](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/DsrAB/seed_refpkg/final_outputs)                     | Dissimilatory sulfite reductase, alpha and beta subunits                                 | 752        | Dissimilatory sulfate reduction and oxidation | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [DsrC](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/DsrC/seed_refpkg/final_outputs)                       |                                                                                          | 341        | Dissimilatory sulfate reduction and oxidation | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [Sat](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/Sat/seed_refpkg/final_outputs)                         | Sulfate adenylyltransferase [PF01747, EC:2.7.7.4]                                        | 254        | Dissimilatory sulfate reduction and oxidation | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [SoxB](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/SoxB/seed_refpkg/final_outputs)                       | S-sulfosulfanyl-L-cysteine sulfohydrolase [TIGR04486]                                    | 1012       | SOX system                                    | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [SoxY](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/SoxY/seed_refpkg/final_outputs)                       | Thiosulfate oxidation carrier protein [TIGR04488,ENOG501RH4J]                            | 364        | SOX system                                    | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+
| [SoxZ](https://github.com/hallamlab/RefPkgs/blob/master/Sulfur_metabolism/SoxZ/seed_refpkg/final_outputs)                       | Thiosulfate oxidation carrier complex protein [TIGR04490,ENOG501N097]                    | 247        | SOX system                                    | S     |
+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+-----------------------------------------------+-------+

:   (\#tab:reference-packages) Available TreeSAPP reference packages
